---
name: Release O2

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  PLUGIN_NAME: o2

jobs:
  build:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        id: build
        run: |
          npm install
          npm run build

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            main.js
            manifest.json
            styles.css
